### ISSUE TITLE
[ERROR] Database "twitch" does not exist 

### ISSUE THREAD

**Issue by Lanisty** [bernardopires/twitch-chat-logger#5]
Hi, I'm getting this error after using fig up for the first time:

bot_1 | Traceback (most recent call last):
bot_1 |   File "main.py", line 24, in <module>
bot_1 |     main()
bot_1 |   File "main.py", line 16, in main
bot_1 |     manager = TwitchManager(channels_amount=args.channels_amount, channels=args.channels, log_filename=args.log_filename)
bot_1 |   File "/code/manager.py", line 28, in **init**
bot_1 |     settings.DATABASE['PASSWORD'])
bot_1 |   File "/code/db_logger.py", line 11, in **init**
bot_1 |     self.conn = psycopg2.connect(host=host, dbname=name, user=user, password=password)
bot_1 |   File "/usr/local/lib/python2.7/site-packages/psycopg2/**init**.py", line 164, in connect
bot_1 |     conn = _connect(dsn, connection_factory=connection_factory, async=async)
bot_1 | psycopg2.OperationalError: could not translate host name "db" to address: Name or service not known
bot_1 | 
twitchchatlogger_bot_1 exited with code 1

when I entered fig up for the second time, I got this error:

db_1  | LOG:  database system was interrupted; last known up at 2016-05-10 19:47:08 UTC
db_1  | LOG:  database system was not properly shut down; automatic recovery in progress
db_1  | LOG:  redo starts at 0/1707678
db_1  | LOG:  invalid record length at 0/1707808
db_1  | LOG:  redo done at 0/17077E0
db_1  | LOG:  last completed transaction was at log time 2016-05-10 19:47:09.662833+00
db_1  | LOG:  MultiXact member wraparound protections are now enabled
db_1  | LOG:  database system is ready to accept connections
db_1  | LOG:  autovacuum launcher started
db_1  | FATAL:  database "twitch" does not exist
bot_1 | Traceback (most recent call last):
bot_1 |   File "main.py", line 24, in <module>
bot_1 |     main()
bot_1 |   File "main.py", line 16, in main
bot_1 |     manager = TwitchManager(channels_amount=args.channels_amount, channels=args.channels, log_filename=args.log_filename)
bot_1 |   File "/code/manager.py", line 28, in **init**
bot_1 |     settings.DATABASE['PASSWORD'])
bot_1 |   File "/code/db_logger.py", line 11, in **init**
bot_1 |     self.conn = psycopg2.connect(host=host, dbname=name, user=user, password=password)
bot_1 |   File "/usr/local/lib/python2.7/site-packages/psycopg2/**init**.py", line 164, in connect
bot_1 |     conn = _connect(dsn, connection_factory=connection_factory, async=async)
bot_1 | psycopg2.OperationalError: FATAL:  database "twitch" does not exist
bot_1 | 
twitchchatlogger_bot_1 exited with code 1

Any idea how this can be solved?

**Comment by juanpflores** [comment]
Did you install Postgress and setup a DB?
