### ISSUE TITLE
ImportError: No module named 'irc'

### ISSUE THREAD

**Issue by aspenrozal** [bernardopires/twitch-chat-logger#7]
First off, thank you for doing this! I love the concept, but am having trouble getting going.

Here is my error:
Traceback (most recent call last):
  File "main.py", line 3, in <module>
    from manager import TwitchManager
  File "E:\MyDocs\GitHub\Twitch-Chat-Logger\twitch-chat-logger\manager.py", line 5, in <module>
    from irc import run_bot, IRCConnection
ImportError: No module named 'irc'

I have installed the requirements.txt successfully. I am not using fig or docker. I have changed the 'HOST' to 'localhost'

Let me know if I can add any more info (I am new to this stuff).
Thank you,

Aspen

**Comment by juanpflores** [comment]
Did you installed everything in the requirements file by running `pip install -requirements.txt`?

**Comment by slacker298** [comment]
Maybe its a windows thing, but the line in the requirements.txt file that gets the irc package 
`-e git://github.com/bernardopires/irc.git#egg=irckit-dev`
puts it all in a folder named "src"

drag the files from /src/icrkit/ to the main directory with the rest of the code and this problem should be solved
